### ISSUE TITLE
NPM publish

### ISSUE THREAD

**Issue by tpluscode** [HydraCG/Heracles.ts#19]
I renamed the old Heracles and I can transfer ownership on the NPM package.

What do you guys think?

**Comment by lanthaler** [comment]
That would be cool

**Comment by tpluscode** [comment]
Give me a username and I'll do it

**Comment by angelo-v** [comment]
It would be great to have this published on NPM. What is in the way?

**Comment by tpluscode** [comment]
@angelo-v I previously called my client Heracles, and so own the [npm package](https://www.npmjs.com/package/heracles). guess it's not really a problem. I can publish there myself just as well

For actual publishing we'd need an npm `prepare` script to transpile a we should be good. Maybe also add filter to publish only the relevant js files.

Let me create a PR with those changes. At which point you will also be able to install from GitHub directly

**Comment by alien-mcl** [comment]
I think on npm we should publish as heracles.ts to be consistent with the
repo.
Still, you can use the lib directly from the github with package.json, i.e.:

"dependencies": { "heracles.ts": "github:HydraCG/Heracles.ts" }

Should work

pon., 7 sty 2019 o 21:34 Tomasz Pluskiewicz <notifications@github.com>
napisał(a):

**Comment by tpluscode** [comment]
No, it will not just work without TypeScript

**Comment by alien-mcl** [comment]
Yep - I'll try to fix it ASAP.

**Comment by tpluscode** [comment]
When #50 is merge then any TypeScrip will be removed from `node_modules`
