### ISSUE TITLE
Question on status of spec and releases

### ISSUE THREAD

**Issue by lambdakris** [HydraCG/Heracles.ts#192]
I wanted to find out about the status of Heracles.ts relative to the spec, especially with regards to releases on NPM. Is there a particular release that ties to the current draft?

**Comment by alien-mcl** [comment]
Unfortunately not - Heracles.ts is somehow behind schedule as I was focused on the spec itself. We're getting close with the spec to Release Candidate state, thus I had no time to work on Heracles.ts / .net to adjust it to the latest spec.

But be assured that Heracles is abandoned - I'll get back to it once the spec is stuffed with last feature waiting in PR.

**Comment by lambdakris** [comment]
Ok, no worries. What do you see as the crucial differences between Hydra as described in the working draft and Hydra as implemented in the cookbook?

Also, is it safe to say that the cookbook is based on v0.2.0 of Heracles.ts?

**Comment by alien-mcl** [comment]
I think the cookbook is indeed close to what Heracles.ts offers. I believe the client is missing a few last features from the spec, but I'll need some time to review what's actually missing. Relative IRI template resolution algorithm is one of the missing things for sure.
