### ISSUE TITLE
Don't mint blank node IDs unless absolutely necessary

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Heracles.ts#21]
Heracles sometimes mints blank node IDs without avoiding collisions with already existing blank node IDs. We either need to do that or stop minting such identifiers as they shouldn't be necessary in the first place.

**Comment by alien-mcl** [comment]
I was thinking about that and I feel that shouldn't be an issue. Indeed in one case, when creating expanded operations with template, we do generate some identifiers, as our current model requires each data model object to have an `iri`. We do generate blank nodes, but:
- these are only valid within a context of hydra client data model
- hydra client's data model cannot be considered as RDF as it is no more a JSON-LD
- identifiers are unique within a `session` (i.e. unless whole application us unloaded)
I think these circumstances are strong enough to avoid issues in future. What do you think?

**Comment by alien-mcl** [comment]
I believe this can be closed as there are no objections for current approach.
