### ISSUE TITLE
Extending from Arrays (Compatibility)

### ISSUE THREAD

**Issue by aJonathanSchneider** [HydraCG/Heracles.ts#26]
Hi everyone,

in a personal project I'm using Heracles, and it runs into an issue with [TypesCollection](https://github.com/HydraCG/Heracles.ts/blob/master/src/DataModel/Collections/TypesCollection.ts). 

The issue comes from directly extending Array, so I've done some research on the matter:
- Extending from Array isn't possible at all on older javascript versions
- It's possible to do this in newer Typescript versions, but if someone uses Babel to transpile, [they must use a plugin](https://stackoverflow.com/questions/33832646/extending-built-in-natives-in-es6-with-babel) , and I haven't yet been able to make it work
- There are [alternatives](https://blog.simontest.net/extend-array-with-typescript-965cc1134b3) to directly extending arrays, such as wrappers. I assume the TypesCollection-type's functionality might grow in the future, wouldn't that be a good alternative?

Hope you all had a good start into 2018!

**Comment by alien-mcl** [comment]
Hi @aJonathanSchneider 

This is a great news that Heracles got some attention! Could you please elaborate more a bit about the issues you're experiencing? Indeed there was a time when extending from raw Arrays caused issues, but I though these times are no more.

In the meanwhile, I'll try to discover any (dis)advantages of extending array and not doing so. Maybe it's not worth of extending it in favor of iterable-like implementation enabling the project to be used on more sophisticated/legacy environments.

**Comment by aJonathanSchneider** [comment]
Hi @alien-mcl ,

yes I've been using it for quite some time now actually.

I've so far been able to get Babel to transpile, but haven't yet tested it on any older browsers. My question is rather what your take on downward compatibility is. The issue with Array seemed to be the only one that couldn't be handled by polyfills at some point any more (the await keyword also needed a polyfill on my side).
Some internet cafés still run Windows XP and an equally old browser, and so some of my future users might be sitting on front of such a machine.

If anyone's runs into the same issues with babel, here are the relevant code snippets:

package.json -devDependencies
`
"@babel/core": "^7.0.0-beta.37",
"@babel/preset-env": "^7.0.0-beta.37",
"@babel/polyfill": "^7.0.0-beta.37",
"@babel/preset-es2015": "^7.0.0-beta.37",
"@babel/preset-react": "^7.0.0-beta.37",
"babel-plugin-transform-builtin-extend": "^1.1.2",`

webpack.config.js -module.rules
`      {
        enforce: 'pre',
        test: /\.js$/,
        loader: "source-map-loader"
      },
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/env',
                "@babel/preset-es2015", '@babel/preset-react'
              ]
            }
          },
          {
            loader: "awesome-typescript-loader"
          },
        ]
      },`

.babelrc
`{
    "plugins": [
        ["babel-plugin-transform-builtin-extend", {
            "globals": ["Error", "Array"]
        }]
    ]
}`

**Comment by alien-mcl** [comment]
I'd personally like to cut off some of the legacy, but if we can have a better compatibility with cheap changes - I'm keen to do it. As I wrote - I'll explore possibilities as I won't die for extended arrays :)
