### ISSUE TITLE
Decide on and document license of this code

### ISSUE THREAD

**Issue by lanthaler** [HydraCG/Heracles.ts#4]
I'd propose to go with MIT. Thoughts? @alien-mcl

**Comment by alien-mcl** [comment]
AFAIK MIT and BSD3 are very similar. I've usually used BSD3, but I have no problem with MIT.

**Comment by lanthaler** [comment]
OK, great. I think this may warrant broader discussion. I added it to the agenda for next week's call.

**Comment by lanthaler** [comment]
RESOLUTION: Use MIT license for Heracles.ts
