### ISSUE TITLE
Are responses fully typed?

### ISSUE THREAD

**Issue by devinrhode2** [HydraCG/Heracles.ts#467]
I'm trying to gauge how good the TS types are in the responses from this client.

The example in the readme doesn't look great:

![CleanShot 2022-09-30 at 10 02 48](https://user-images.githubusercontent.com/539816/193299473-2fb7cc3e-b739-4abc-ae4f-3fb54bca6e91.png)

Although there are a lot of .d.ts files in this package, so there's at least some level of type defs added.

**Comment by devinrhode2** [comment]
members is not typed:
![CleanShot 2022-09-30 at 10 25 14](https://user-images.githubusercontent.com/539816/193303876-442ccf91-619a-47d3-a81c-89094fc44561.png)

**Comment by devinrhode2** [comment]
This `view` thing has types, that's good
![CleanShot 2022-09-30 at 10 27 48](https://user-images.githubusercontent.com/539816/193304496-38d607c4-db61-440b-8691-456c572363d8.png)

![CleanShot 2022-09-30 at 10 28 25](https://user-images.githubusercontent.com/539816/193304510-620dc6a4-eaa4-4006-aa37-745607c74a7f.png)

**Comment by alien-mcl** [comment]
Thanks @devinrhode2. What IDE is that? Is there any place I could your project opened so I can figure it out on what's going on? Whole project is in TS so type hints should be native without any other additional steps.

**Comment by devinrhode2** [comment]
Just Vscode.

**Comment by alien-mcl** [comment]
And the project? What should I do to reproduce? Simple node.js setup with gh linked?

**Comment by devinrhode2** [comment]
You could use vite cra next, CodeSandbox, etc
You could probably also just create an empty folder
Npm install this thing
Add an empty tsconfig.json:
{}

Create an index.tsx file
Paste example from docs

**Comment by alien-mcl** [comment]
Oh, OK, I see what's wrong - the example is outdated. Instead
```ts
for (const link of resource.hypermedia.links)
```

it should be
```ts
for (const link of resource.links)
```

![VSCodeTypeHints2](https://user-images.githubusercontent.com/8111925/201315552-9561ad9b-52a0-40ca-bf6b-43cf5a48dc87.png)
![VSCodeTypeHints](https://user-images.githubusercontent.com/8111925/201315558-34eb9e22-a535-495c-8773-1404e6be5da5.png)

I'll try to have it updated ASAP.
