### ISSUE TITLE
Document how to install and use Heracles.ts

### ISSUE THREAD

**Issue by angelo-v** [HydraCG/Heracles.ts#49]
Please provide some "Quick Start" and examples of how to install and use Heracles.ts. The generated TypeDoc is not really helpful to get started.

**Comment by alien-mcl** [comment]
I've published an early release of the Heracles.ts to npm under [hydra-cg](https://www.npmjs.com/package/@hydra-cg/heracles.ts) scope. There is also some quick guide in the readme.md in the root of the repo. I hope it will help.

**Comment by alien-mcl** [comment]
I think what's already available should be enough to acknowledge this issue as closed. If there is still something more you'd like to see, feel free to reopen it.
