### ISSUE TITLE
Consider using/merging the api-doc-parser library

### ISSUE THREAD

**Issue by dunglas** [HydraCG/Heracles.ts#6]
Hi everybody,

Some months ago I published a Hydra client library we use for [API Platform](https://api-platform.com)'s client-side tools: https://github.com/dunglas/api-doc-parser

It looks very similar to what you are doing (but uses ES6 + Flow instead of TypeScript). It is already used by two of our tools:

* An admin for Hydra APIs: https://github.com/dunglas/api-doc-parser
* A ReactJS code generator for Hydra APIs: https://github.com/api-platform/generate-crud

I looked quickly to your implementation, and it looks really similar to ours. The main difference is that we designed our library with an abstraction layer to be able to consume other formats like Swagger or JSONAPI (but it's not done yet).
Can we find a way to collaborate? It's useless to duplicate the effort.

**Comment by lanthaler** [comment]
Indeed, there seems to be quite some overlap even though the names suggest that we might have slightly different goals. Heracles is intended not only to fetch/parse the API documentation, but to be used for all interactions with the API too. So eventually, it should support all Hydra features (such as iterating over paginated collections) natively. Would you be willing to contribute code to Heracles? I think that would be the simplest way to get a collaboration started.

**Comment by dunglas** [comment]
Why not but I don't know TypeScript :)

**Comment by lanthaler** [comment]
If you know JavaScript and PHP, you more or less know TypeScript too.

**Comment by lanthaler** [comment]
@dunglas, is there anything else you would like to discuss here or should we close this issue?

**Comment by dunglas** [comment]
Thanks for the answer!
